# Generated by Django 4.2.11 on 2024-03-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_compra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compra',
            new_name='Precio',
        ),
    ]
